eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka
    fetchRegistry: true
  instance: 
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 0
feign:
  hystrix:
    enabled: true
---
spring:
  profiles: staging
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka
---
spring:
  profiles: performance
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.176:8761/eureka/eureka
---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka
